version: '3.8'

services:
  db:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    ports:
      - "54321:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8001:8080"
